name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '6.0'
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v